on:
  schedule:
    # ⏰ Cron configurado para rodar de hora em hora (Minuto 0)
    # Das 13:00 UTC às 21:00 UTC -> Equivale a 10:00h até 18:00h de Brasília
    - cron: '0 13-21 * * 1-5'
  
  workflow_dispatch:
